# Bacon configuration for Meridian
# https://dystroy.org/bacon/

[jobs.check]
command = ["cargo", "check", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = ["cargo", "clippy", "--all-targets", "--color", "always", "--", "-D", "warnings"]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--color", "always"]
need_stdout = true

[jobs.nextest]
command = ["cargo", "nextest", "run", "--color", "always"]
need_stdout = true

[jobs.doc]
command = ["cargo", "doc", "--no-deps", "--color", "always"]
need_stdout = false

[jobs.run]
command = ["cargo", "run", "--color", "always"]
need_stdout = true
allow_hierarchical_json = true

[keybindings]
c = "job:clippy"
t = "job:test"
n = "job:nextest"
d = "job:doc"
r = "job:run"

[default]
job = "check"
